
drop table NHANVIEN 

/*CREATE TABLE NHANVIEN(
	MANV NVARCHAR(10) PRIMARY KEY, 
	HOTEN NVARCHAR(50) NOT NULL,
	SDT VARCHAR(11) NULL,
	CHUCVU VARCHAR(50) NULL
)
*/

SELECT * FROM NHANVIEN 


SELECT CONCAT('NV', RIGHT(CONCAT('0000',ISNULL(right(max(MANV),4),0) + 1),4))
FROM dbo.NHANVIEN WHERE MANV LIKE 'NV%' 