CREATE TABLE NHANVIEN(
    IDNO int PRIMARY KEY identity,
	MANV AS 'NV' + RIGHT('000000' + CAST(IDNO AS VARCHAR), 6),
	HOTEN NVARCHAR(50) NOT NULL,
	SDT VARCHAR(11) NULL,
	CHUCVU VARCHAR(50) NULL
)

DROP TABLE NHOMMONAN 
Select * from NHANVIEN

CREATE TABLE NHOMMONAN 
( MANHOM INT PRIMARY KEY identity,
TENNHOM NVARCHAR(50))

Select * from NHOMMONAN 
DROP TABLE MONAN 

CREATE TABLE MONAN(
    IDNO int PRIMARY KEY identity,
	MAMON AS 'D' + RIGHT('00000' + CAST(IDNO AS VARCHAR), 5),
	TENMON NVARCHAR(50) ,
	GIA FLOAT,
	HINHANH IMAGE ,
	MANHOM INT 
)

select IDNO, MAMON,TENMON,GIA, c.TENNHOM from MONAN p inner join NHOMMONAN c ON c.MANHOM = p.MANHOM 
select MONAN.IDNO, MONAN.MAMON,MONAN.TENMON,MONAN.GIA,NHOMMONAN.MANHOM,NHOMMONAN.TENNHOM from MONAN, NHOMMONAN where MONAN.MANHOM = NHOMMONAN.MANHOM 












